//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WhpWebServiceImpServiceSoapBinding", Namespace="http://service.hhjt.com/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(returnData))]
public partial class WhpWebServiceImpService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback queryInventoryStaByAreaOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryWHP2828OperationCompleted;
    
    private System.Threading.SendOrPostCallback queryInventoryStaByGradeOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryWHPGradeOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryWarehouseStaBy2828OperationCompleted;
    
    private System.Threading.SendOrPostCallback queryProReviewDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryAreaOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryWarehouseOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryInventoryDetailOperationCompleted;
    
    private System.Threading.SendOrPostCallback queryInventoryStaBy2828OperationCompleted;
    
    /// <remarks/>
    public WhpWebServiceImpService() {
        this.Url = "http://180.168.107.59:8180/whp/WhpWebSer";
    }
    
    /// <remarks/>
    public event queryInventoryStaByAreaCompletedEventHandler queryInventoryStaByAreaCompleted;
    
    /// <remarks/>
    public event queryWHP2828CompletedEventHandler queryWHP2828Completed;
    
    /// <remarks/>
    public event queryInventoryStaByGradeCompletedEventHandler queryInventoryStaByGradeCompleted;
    
    /// <remarks/>
    public event queryWHPGradeCompletedEventHandler queryWHPGradeCompleted;
    
    /// <remarks/>
    public event queryWarehouseStaBy2828CompletedEventHandler queryWarehouseStaBy2828Completed;
    
    /// <remarks/>
    public event queryProReviewDataCompletedEventHandler queryProReviewDataCompleted;
    
    /// <remarks/>
    public event queryAreaCompletedEventHandler queryAreaCompleted;
    
    /// <remarks/>
    public event queryWarehouseCompletedEventHandler queryWarehouseCompleted;
    
    /// <remarks/>
    public event queryInventoryDetailCompletedEventHandler queryInventoryDetailCompleted;
    
    /// <remarks/>
    public event queryInventoryStaBy2828CompletedEventHandler queryInventoryStaBy2828Completed;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public inventStaByAreaListRtObj queryInventoryStaByArea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] decimal grade, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool gradeSpecified) {
        object[] results = this.Invoke("queryInventoryStaByArea", new object[] {
                    grade,
                    gradeSpecified});
        return ((inventStaByAreaListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryInventoryStaByArea(decimal grade, bool gradeSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryInventoryStaByArea", new object[] {
                    grade,
                    gradeSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public inventStaByAreaListRtObj EndqueryInventoryStaByArea(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((inventStaByAreaListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryInventoryStaByAreaAsync(decimal grade, bool gradeSpecified) {
        this.queryInventoryStaByAreaAsync(grade, gradeSpecified, null);
    }
    
    /// <remarks/>
    public void queryInventoryStaByAreaAsync(decimal grade, bool gradeSpecified, object userState) {
        if ((this.queryInventoryStaByAreaOperationCompleted == null)) {
            this.queryInventoryStaByAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryInventoryStaByAreaOperationCompleted);
        }
        this.InvokeAsync("queryInventoryStaByArea", new object[] {
                    grade,
                    gradeSpecified}, this.queryInventoryStaByAreaOperationCompleted, userState);
    }
    
    private void OnqueryInventoryStaByAreaOperationCompleted(object arg) {
        if ((this.queryInventoryStaByAreaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryInventoryStaByAreaCompleted(this, new queryInventoryStaByAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public whp2828ListRtObj queryWHP2828([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string whpNbr) {
        object[] results = this.Invoke("queryWHP2828", new object[] {
                    whpNbr});
        return ((whp2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryWHP2828(string whpNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryWHP2828", new object[] {
                    whpNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public whp2828ListRtObj EndqueryWHP2828(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((whp2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryWHP2828Async(string whpNbr) {
        this.queryWHP2828Async(whpNbr, null);
    }
    
    /// <remarks/>
    public void queryWHP2828Async(string whpNbr, object userState) {
        if ((this.queryWHP2828OperationCompleted == null)) {
            this.queryWHP2828OperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWHP2828OperationCompleted);
        }
        this.InvokeAsync("queryWHP2828", new object[] {
                    whpNbr}, this.queryWHP2828OperationCompleted, userState);
    }
    
    private void OnqueryWHP2828OperationCompleted(object arg) {
        if ((this.queryWHP2828Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryWHP2828Completed(this, new queryWHP2828CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public inventStaByGradeListRtObj queryInventoryStaByGrade([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] decimal grade, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool gradeSpecified) {
        object[] results = this.Invoke("queryInventoryStaByGrade", new object[] {
                    grade,
                    gradeSpecified});
        return ((inventStaByGradeListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryInventoryStaByGrade(decimal grade, bool gradeSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryInventoryStaByGrade", new object[] {
                    grade,
                    gradeSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public inventStaByGradeListRtObj EndqueryInventoryStaByGrade(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((inventStaByGradeListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryInventoryStaByGradeAsync(decimal grade, bool gradeSpecified) {
        this.queryInventoryStaByGradeAsync(grade, gradeSpecified, null);
    }
    
    /// <remarks/>
    public void queryInventoryStaByGradeAsync(decimal grade, bool gradeSpecified, object userState) {
        if ((this.queryInventoryStaByGradeOperationCompleted == null)) {
            this.queryInventoryStaByGradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryInventoryStaByGradeOperationCompleted);
        }
        this.InvokeAsync("queryInventoryStaByGrade", new object[] {
                    grade,
                    gradeSpecified}, this.queryInventoryStaByGradeOperationCompleted, userState);
    }
    
    private void OnqueryInventoryStaByGradeOperationCompleted(object arg) {
        if ((this.queryInventoryStaByGradeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryInventoryStaByGradeCompleted(this, new queryInventoryStaByGradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public whpGradeListRtObj queryWHPGrade([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] decimal gradeNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool gradeNbrSpecified) {
        object[] results = this.Invoke("queryWHPGrade", new object[] {
                    gradeNbr,
                    gradeNbrSpecified});
        return ((whpGradeListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryWHPGrade(decimal gradeNbr, bool gradeNbrSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryWHPGrade", new object[] {
                    gradeNbr,
                    gradeNbrSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public whpGradeListRtObj EndqueryWHPGrade(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((whpGradeListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryWHPGradeAsync(decimal gradeNbr, bool gradeNbrSpecified) {
        this.queryWHPGradeAsync(gradeNbr, gradeNbrSpecified, null);
    }
    
    /// <remarks/>
    public void queryWHPGradeAsync(decimal gradeNbr, bool gradeNbrSpecified, object userState) {
        if ((this.queryWHPGradeOperationCompleted == null)) {
            this.queryWHPGradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWHPGradeOperationCompleted);
        }
        this.InvokeAsync("queryWHPGrade", new object[] {
                    gradeNbr,
                    gradeNbrSpecified}, this.queryWHPGradeOperationCompleted, userState);
    }
    
    private void OnqueryWHPGradeOperationCompleted(object arg) {
        if ((this.queryWHPGradeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryWHPGradeCompleted(this, new queryWHPGradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public wareHouseStaBy2828ListRtObj queryWarehouseStaBy2828([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string areaNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string wareHouseNbr) {
        object[] results = this.Invoke("queryWarehouseStaBy2828", new object[] {
                    areaNbr,
                    wareHouseNbr});
        return ((wareHouseStaBy2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryWarehouseStaBy2828(string areaNbr, string wareHouseNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryWarehouseStaBy2828", new object[] {
                    areaNbr,
                    wareHouseNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public wareHouseStaBy2828ListRtObj EndqueryWarehouseStaBy2828(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((wareHouseStaBy2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryWarehouseStaBy2828Async(string areaNbr, string wareHouseNbr) {
        this.queryWarehouseStaBy2828Async(areaNbr, wareHouseNbr, null);
    }
    
    /// <remarks/>
    public void queryWarehouseStaBy2828Async(string areaNbr, string wareHouseNbr, object userState) {
        if ((this.queryWarehouseStaBy2828OperationCompleted == null)) {
            this.queryWarehouseStaBy2828OperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWarehouseStaBy2828OperationCompleted);
        }
        this.InvokeAsync("queryWarehouseStaBy2828", new object[] {
                    areaNbr,
                    wareHouseNbr}, this.queryWarehouseStaBy2828OperationCompleted, userState);
    }
    
    private void OnqueryWarehouseStaBy2828OperationCompleted(object arg) {
        if ((this.queryWarehouseStaBy2828Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryWarehouseStaBy2828Completed(this, new queryWarehouseStaBy2828CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public proReviewListRtObj queryProReviewData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string whpProNbr) {
        object[] results = this.Invoke("queryProReviewData", new object[] {
                    whpProNbr});
        return ((proReviewListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryProReviewData(string whpProNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryProReviewData", new object[] {
                    whpProNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public proReviewListRtObj EndqueryProReviewData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((proReviewListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryProReviewDataAsync(string whpProNbr) {
        this.queryProReviewDataAsync(whpProNbr, null);
    }
    
    /// <remarks/>
    public void queryProReviewDataAsync(string whpProNbr, object userState) {
        if ((this.queryProReviewDataOperationCompleted == null)) {
            this.queryProReviewDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryProReviewDataOperationCompleted);
        }
        this.InvokeAsync("queryProReviewData", new object[] {
                    whpProNbr}, this.queryProReviewDataOperationCompleted, userState);
    }
    
    private void OnqueryProReviewDataOperationCompleted(object arg) {
        if ((this.queryProReviewDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryProReviewDataCompleted(this, new queryProReviewDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public areaListRtObj queryArea([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string areaNbr) {
        object[] results = this.Invoke("queryArea", new object[] {
                    areaNbr});
        return ((areaListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryArea(string areaNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryArea", new object[] {
                    areaNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public areaListRtObj EndqueryArea(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((areaListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryAreaAsync(string areaNbr) {
        this.queryAreaAsync(areaNbr, null);
    }
    
    /// <remarks/>
    public void queryAreaAsync(string areaNbr, object userState) {
        if ((this.queryAreaOperationCompleted == null)) {
            this.queryAreaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAreaOperationCompleted);
        }
        this.InvokeAsync("queryArea", new object[] {
                    areaNbr}, this.queryAreaOperationCompleted, userState);
    }
    
    private void OnqueryAreaOperationCompleted(object arg) {
        if ((this.queryAreaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryAreaCompleted(this, new queryAreaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public warehouseListRtObj queryWarehouse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string areaNbr) {
        object[] results = this.Invoke("queryWarehouse", new object[] {
                    areaNbr});
        return ((warehouseListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryWarehouse(string areaNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryWarehouse", new object[] {
                    areaNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public warehouseListRtObj EndqueryWarehouse(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((warehouseListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryWarehouseAsync(string areaNbr) {
        this.queryWarehouseAsync(areaNbr, null);
    }
    
    /// <remarks/>
    public void queryWarehouseAsync(string areaNbr, object userState) {
        if ((this.queryWarehouseOperationCompleted == null)) {
            this.queryWarehouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWarehouseOperationCompleted);
        }
        this.InvokeAsync("queryWarehouse", new object[] {
                    areaNbr}, this.queryWarehouseOperationCompleted, userState);
    }
    
    private void OnqueryWarehouseOperationCompleted(object arg) {
        if ((this.queryWarehouseCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryWarehouseCompleted(this, new queryWarehouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public inventoryDetailListRtObj queryInventoryDetail([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string areaNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string wareHouseNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string binNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string whpNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string whpProNbr) {
        object[] results = this.Invoke("queryInventoryDetail", new object[] {
                    areaNbr,
                    wareHouseNbr,
                    binNbr,
                    whpNbr,
                    whpProNbr});
        return ((inventoryDetailListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryInventoryDetail(string areaNbr, string wareHouseNbr, string binNbr, string whpNbr, string whpProNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryInventoryDetail", new object[] {
                    areaNbr,
                    wareHouseNbr,
                    binNbr,
                    whpNbr,
                    whpProNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public inventoryDetailListRtObj EndqueryInventoryDetail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((inventoryDetailListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryInventoryDetailAsync(string areaNbr, string wareHouseNbr, string binNbr, string whpNbr, string whpProNbr) {
        this.queryInventoryDetailAsync(areaNbr, wareHouseNbr, binNbr, whpNbr, whpProNbr, null);
    }
    
    /// <remarks/>
    public void queryInventoryDetailAsync(string areaNbr, string wareHouseNbr, string binNbr, string whpNbr, string whpProNbr, object userState) {
        if ((this.queryInventoryDetailOperationCompleted == null)) {
            this.queryInventoryDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryInventoryDetailOperationCompleted);
        }
        this.InvokeAsync("queryInventoryDetail", new object[] {
                    areaNbr,
                    wareHouseNbr,
                    binNbr,
                    whpNbr,
                    whpProNbr}, this.queryInventoryDetailOperationCompleted, userState);
    }
    
    private void OnqueryInventoryDetailOperationCompleted(object arg) {
        if ((this.queryInventoryDetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryInventoryDetailCompleted(this, new queryInventoryDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.hhjt.com/", ResponseNamespace="http://service.hhjt.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public inventStaBy2828ListRtObj queryInventoryStaBy2828([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string areaNbr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string whpNbr) {
        object[] results = this.Invoke("queryInventoryStaBy2828", new object[] {
                    areaNbr,
                    whpNbr});
        return ((inventStaBy2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginqueryInventoryStaBy2828(string areaNbr, string whpNbr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("queryInventoryStaBy2828", new object[] {
                    areaNbr,
                    whpNbr}, callback, asyncState);
    }
    
    /// <remarks/>
    public inventStaBy2828ListRtObj EndqueryInventoryStaBy2828(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((inventStaBy2828ListRtObj)(results[0]));
    }
    
    /// <remarks/>
    public void queryInventoryStaBy2828Async(string areaNbr, string whpNbr) {
        this.queryInventoryStaBy2828Async(areaNbr, whpNbr, null);
    }
    
    /// <remarks/>
    public void queryInventoryStaBy2828Async(string areaNbr, string whpNbr, object userState) {
        if ((this.queryInventoryStaBy2828OperationCompleted == null)) {
            this.queryInventoryStaBy2828OperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryInventoryStaBy2828OperationCompleted);
        }
        this.InvokeAsync("queryInventoryStaBy2828", new object[] {
                    areaNbr,
                    whpNbr}, this.queryInventoryStaBy2828OperationCompleted, userState);
    }
    
    private void OnqueryInventoryStaBy2828OperationCompleted(object arg) {
        if ((this.queryInventoryStaBy2828Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.queryInventoryStaBy2828Completed(this, new queryInventoryStaBy2828CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventStaByAreaListRtObj : returnData {
    
    private inventoryStaDataByArea[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public inventoryStaDataByArea[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventoryStaDataByArea {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string companyNameField;
    
    private string whpGradeField;
    
    private decimal whpNumField;
    
    private bool whpNumFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string companyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpGrade {
        get {
            return this.whpGradeField;
        }
        set {
            this.whpGradeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpNum {
        get {
            return this.whpNumField;
        }
        set {
            this.whpNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpNumSpecified {
        get {
            return this.whpNumFieldSpecified;
        }
        set {
            this.whpNumFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventoryStaDataBy2828 {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private decimal numField;
    
    private bool numFieldSpecified;
    
    private string whpNameField;
    
    private string whpNbrField;
    
    private string whpNickNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numSpecified {
        get {
            return this.numFieldSpecified;
        }
        set {
            this.numFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpName {
        get {
            return this.whpNameField;
        }
        set {
            this.whpNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNbr {
        get {
            return this.whpNbrField;
        }
        set {
            this.whpNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNickName {
        get {
            return this.whpNickNameField;
        }
        set {
            this.whpNickNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventoryDetailData {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string batchNbrField;
    
    private string bingNbrField;
    
    private System.DateTime countDateField;
    
    private bool countDateFieldSpecified;
    
    private string unitField;
    
    private string wareHouseNameField;
    
    private string wareHouseNbrField;
    
    private string whpNameField;
    
    private string whpNbrField;
    
    private string whpNickNameField;
    
    private decimal whpNumField;
    
    private bool whpNumFieldSpecified;
    
    private string whpProNbrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string batchNbr {
        get {
            return this.batchNbrField;
        }
        set {
            this.batchNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bingNbr {
        get {
            return this.bingNbrField;
        }
        set {
            this.bingNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime countDate {
        get {
            return this.countDateField;
        }
        set {
            this.countDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countDateSpecified {
        get {
            return this.countDateFieldSpecified;
        }
        set {
            this.countDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string wareHouseName {
        get {
            return this.wareHouseNameField;
        }
        set {
            this.wareHouseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string wareHouseNbr {
        get {
            return this.wareHouseNbrField;
        }
        set {
            this.wareHouseNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpName {
        get {
            return this.whpNameField;
        }
        set {
            this.whpNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNbr {
        get {
            return this.whpNbrField;
        }
        set {
            this.whpNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNickName {
        get {
            return this.whpNickNameField;
        }
        set {
            this.whpNickNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpNum {
        get {
            return this.whpNumField;
        }
        set {
            this.whpNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpNumSpecified {
        get {
            return this.whpNumFieldSpecified;
        }
        set {
            this.whpNumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpProNbr {
        get {
            return this.whpProNbrField;
        }
        set {
            this.whpProNbrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class warehouseData {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string warehouseGradeNameField;
    
    private string warehouseNameField;
    
    private string warehouseNbrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseGradeName {
        get {
            return this.warehouseGradeNameField;
        }
        set {
            this.warehouseGradeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseName {
        get {
            return this.warehouseNameField;
        }
        set {
            this.warehouseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseNbr {
        get {
            return this.warehouseNbrField;
        }
        set {
            this.warehouseNbrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class areaData {
    
    private string addrField;
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string companyNameField;
    
    private string contactNameField;
    
    private string contactTelephoneField;
    
    private decimal latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private decimal longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private string memoField;
    
    private string temp1Field;
    
    private string temp2Field;
    
    private string temp3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addr {
        get {
            return this.addrField;
        }
        set {
            this.addrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string companyName {
        get {
            return this.companyNameField;
        }
        set {
            this.companyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contactName {
        get {
            return this.contactNameField;
        }
        set {
            this.contactNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string contactTelephone {
        get {
            return this.contactTelephoneField;
        }
        set {
            this.contactTelephoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string memo {
        get {
            return this.memoField;
        }
        set {
            this.memoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string temp1 {
        get {
            return this.temp1Field;
        }
        set {
            this.temp1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string temp2 {
        get {
            return this.temp2Field;
        }
        set {
            this.temp2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string temp3 {
        get {
            return this.temp3Field;
        }
        set {
            this.temp3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class proReviewGateData {
    
    private System.DateTime gateDateField;
    
    private bool gateDateFieldSpecified;
    
    private string gateNbrField;
    
    private string gateOpTypeField;
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime gateDate {
        get {
            return this.gateDateField;
        }
        set {
            this.gateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gateDateSpecified {
        get {
            return this.gateDateFieldSpecified;
        }
        set {
            this.gateDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gateNbr {
        get {
            return this.gateNbrField;
        }
        set {
            this.gateNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string gateOpType {
        get {
            return this.gateOpTypeField;
        }
        set {
            this.gateOpTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class proReviewData {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string batchNbrField;
    
    private string carNBrField;
    
    private string carTypeField;
    
    private string dgpermitNbrField;
    
    private string disCompanyNbrField;
    
    private string disCompayNameField;
    
    private string disNameField;
    
    private string driverField;
    
    private System.DateTime opDateField;
    
    private bool opDateFieldSpecified;
    
    private string opTypeField;
    
    private string ownerCompanyNameField;
    
    private string ownerCompanyNbrField;
    
    private string unitField;
    
    private string warehouseListNbrField;
    
    private string whpNameField;
    
    private string whpNbrField;
    
    private string whpNickNameField;
    
    private decimal whpNumField;
    
    private bool whpNumFieldSpecified;
    
    private string whpProNbrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string batchNbr {
        get {
            return this.batchNbrField;
        }
        set {
            this.batchNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string carNBr {
        get {
            return this.carNBrField;
        }
        set {
            this.carNBrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string carType {
        get {
            return this.carTypeField;
        }
        set {
            this.carTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dgpermitNbr {
        get {
            return this.dgpermitNbrField;
        }
        set {
            this.dgpermitNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string disCompanyNbr {
        get {
            return this.disCompanyNbrField;
        }
        set {
            this.disCompanyNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string disCompayName {
        get {
            return this.disCompayNameField;
        }
        set {
            this.disCompayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string disName {
        get {
            return this.disNameField;
        }
        set {
            this.disNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string driver {
        get {
            return this.driverField;
        }
        set {
            this.driverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime opDate {
        get {
            return this.opDateField;
        }
        set {
            this.opDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool opDateSpecified {
        get {
            return this.opDateFieldSpecified;
        }
        set {
            this.opDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string opType {
        get {
            return this.opTypeField;
        }
        set {
            this.opTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ownerCompanyName {
        get {
            return this.ownerCompanyNameField;
        }
        set {
            this.ownerCompanyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ownerCompanyNbr {
        get {
            return this.ownerCompanyNbrField;
        }
        set {
            this.ownerCompanyNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseListNbr {
        get {
            return this.warehouseListNbrField;
        }
        set {
            this.warehouseListNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpName {
        get {
            return this.whpNameField;
        }
        set {
            this.whpNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNbr {
        get {
            return this.whpNbrField;
        }
        set {
            this.whpNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNickName {
        get {
            return this.whpNickNameField;
        }
        set {
            this.whpNickNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpNum {
        get {
            return this.whpNumField;
        }
        set {
            this.whpNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpNumSpecified {
        get {
            return this.whpNumFieldSpecified;
        }
        set {
            this.whpNumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpProNbr {
        get {
            return this.whpProNbrField;
        }
        set {
            this.whpProNbrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class wareHouseStaDataBy2828 {
    
    private string areaNameField;
    
    private string areaNbrField;
    
    private string warehouseNameField;
    
    private string warehouseNbrField;
    
    private string whpNameField;
    
    private string whpNbrField;
    
    private string whpNickNameField;
    
    private decimal whpNumField;
    
    private bool whpNumFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaName {
        get {
            return this.areaNameField;
        }
        set {
            this.areaNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string areaNbr {
        get {
            return this.areaNbrField;
        }
        set {
            this.areaNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseName {
        get {
            return this.warehouseNameField;
        }
        set {
            this.warehouseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string warehouseNbr {
        get {
            return this.warehouseNbrField;
        }
        set {
            this.warehouseNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpName {
        get {
            return this.whpNameField;
        }
        set {
            this.whpNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNbr {
        get {
            return this.whpNbrField;
        }
        set {
            this.whpNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNickName {
        get {
            return this.whpNickNameField;
        }
        set {
            this.whpNickNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpNum {
        get {
            return this.whpNumField;
        }
        set {
            this.whpNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpNumSpecified {
        get {
            return this.whpNumFieldSpecified;
        }
        set {
            this.whpNumFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class whpGradeData {
    
    private string whpGradeNameField;
    
    private decimal whpGradeNbrField;
    
    private bool whpGradeNbrFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpGradeName {
        get {
            return this.whpGradeNameField;
        }
        set {
            this.whpGradeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpGradeNbr {
        get {
            return this.whpGradeNbrField;
        }
        set {
            this.whpGradeNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpGradeNbrSpecified {
        get {
            return this.whpGradeNbrFieldSpecified;
        }
        set {
            this.whpGradeNbrFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventoryStaDataByGrade {
    
    private string whpGradeNameField;
    
    private decimal whpNumField;
    
    private bool whpNumFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpGradeName {
        get {
            return this.whpGradeNameField;
        }
        set {
            this.whpGradeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpNum {
        get {
            return this.whpNumField;
        }
        set {
            this.whpNumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpNumSpecified {
        get {
            return this.whpNumFieldSpecified;
        }
        set {
            this.whpNumFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class whp2828Data {
    
    private string casNbrField;
    
    private string psField;
    
    private string unNbrField;
    
    private string whpGradeNameField;
    
    private decimal whpGradeNbrField;
    
    private bool whpGradeNbrFieldSpecified;
    
    private string whpNameField;
    
    private string whpNbrField;
    
    private string whpNickNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string casNbr {
        get {
            return this.casNbrField;
        }
        set {
            this.casNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ps {
        get {
            return this.psField;
        }
        set {
            this.psField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string unNbr {
        get {
            return this.unNbrField;
        }
        set {
            this.unNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpGradeName {
        get {
            return this.whpGradeNameField;
        }
        set {
            this.whpGradeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal whpGradeNbr {
        get {
            return this.whpGradeNbrField;
        }
        set {
            this.whpGradeNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool whpGradeNbrSpecified {
        get {
            return this.whpGradeNbrFieldSpecified;
        }
        set {
            this.whpGradeNbrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpName {
        get {
            return this.whpNameField;
        }
        set {
            this.whpNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNbr {
        get {
            return this.whpNbrField;
        }
        set {
            this.whpNbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string whpNickName {
        get {
            return this.whpNickNameField;
        }
        set {
            this.whpNickNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(inventStaBy2828ListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(inventoryDetailListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(warehouseListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(areaListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(proReviewListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(wareHouseStaBy2828ListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(whpGradeListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(inventStaByGradeListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(whp2828ListRtObj))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(inventStaByAreaListRtObj))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class returnData {
    
    private int retCodeField;
    
    private string retInfoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int retCode {
        get {
            return this.retCodeField;
        }
        set {
            this.retCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string retInfo {
        get {
            return this.retInfoField;
        }
        set {
            this.retInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventStaBy2828ListRtObj : returnData {
    
    private inventoryStaDataBy2828[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public inventoryStaDataBy2828[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventoryDetailListRtObj : returnData {
    
    private inventoryDetailData[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public inventoryDetailData[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class warehouseListRtObj : returnData {
    
    private warehouseData[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public warehouseData[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class areaListRtObj : returnData {
    
    private areaData[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public areaData[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class proReviewListRtObj : returnData {
    
    private proReviewData[] reviewDataField;
    
    private proReviewGateData[] reviewGateDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reviewData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public proReviewData[] reviewData {
        get {
            return this.reviewDataField;
        }
        set {
            this.reviewDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("reviewGateData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public proReviewGateData[] reviewGateData {
        get {
            return this.reviewGateDataField;
        }
        set {
            this.reviewGateDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class wareHouseStaBy2828ListRtObj : returnData {
    
    private wareHouseStaDataBy2828[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public wareHouseStaDataBy2828[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class whpGradeListRtObj : returnData {
    
    private whpGradeData[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public whpGradeData[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class inventStaByGradeListRtObj : returnData {
    
    private inventoryStaDataByGrade[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public inventoryStaDataByGrade[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.hhjt.com/")]
public partial class whp2828ListRtObj : returnData {
    
    private whp2828Data[] retDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public whp2828Data[] retData {
        get {
            return this.retDataField;
        }
        set {
            this.retDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryInventoryStaByAreaCompletedEventHandler(object sender, queryInventoryStaByAreaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryInventoryStaByAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryInventoryStaByAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public inventStaByAreaListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((inventStaByAreaListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryWHP2828CompletedEventHandler(object sender, queryWHP2828CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryWHP2828CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryWHP2828CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public whp2828ListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((whp2828ListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryInventoryStaByGradeCompletedEventHandler(object sender, queryInventoryStaByGradeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryInventoryStaByGradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryInventoryStaByGradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public inventStaByGradeListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((inventStaByGradeListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryWHPGradeCompletedEventHandler(object sender, queryWHPGradeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryWHPGradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryWHPGradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public whpGradeListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((whpGradeListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryWarehouseStaBy2828CompletedEventHandler(object sender, queryWarehouseStaBy2828CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryWarehouseStaBy2828CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryWarehouseStaBy2828CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public wareHouseStaBy2828ListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((wareHouseStaBy2828ListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryProReviewDataCompletedEventHandler(object sender, queryProReviewDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryProReviewDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryProReviewDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public proReviewListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((proReviewListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryAreaCompletedEventHandler(object sender, queryAreaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryAreaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryAreaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public areaListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((areaListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryWarehouseCompletedEventHandler(object sender, queryWarehouseCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryWarehouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryWarehouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public warehouseListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((warehouseListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryInventoryDetailCompletedEventHandler(object sender, queryInventoryDetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryInventoryDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryInventoryDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public inventoryDetailListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((inventoryDetailListRtObj)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void queryInventoryStaBy2828CompletedEventHandler(object sender, queryInventoryStaBy2828CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class queryInventoryStaBy2828CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal queryInventoryStaBy2828CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public inventStaBy2828ListRtObj Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((inventStaBy2828ListRtObj)(this.results[0]));
        }
    }
}
